POST http://localhost:3001/api/notes
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjIsImlhdCI6MTY2MjYyNDcwMX0.Nov1I1NyX57PA08tpSt0J4cwrTz9xX-_QNPNqWstjNs

{
    "content":"This is the fourth content created using token created by sudesh",
    "important":false

}

###
PUT http://localhost:3001/api/notes/4
Content-type: application/json

{
    "important":false

}

###
DELETE http://localhost:3001/api/notes/4


### 
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username":"prisoner",
    "name":"paul"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"admin",
    "password":"secret"
}


